

server.port=8080
spring.web.resources.static-locations=classpath:/resources/, classpath:/static/, classpath:/static/photo, classpath:/static/file

spring.datasource.url=jdbc:postgresql://localhost:5432/mcpeserver
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

app.jwtSecret=abjksakkdvyavrbhgabdbyarbybvhdvchzbxjcrehdgvvzmxgrcsyvbzdhgfsjdfgbnzxvcvhjyfdg
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=2592000000
app.jwtIssuser=MCPEServer

# user access token insert into api endpoint
app.userAccessToken=chtotebezsesnugno

app.uploadPhotoPath=D:/mcpe/photos/
app.uploadFilePath=D:/mcpe/files/
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB


app.host=http://localhost
logging.file.name = D:/mcpe/server-log/applog.log