server.port=8443
security.require-ssl=true
server.ssl.key-store=/etc/letsencrypt/live/minecraftpoketedition.top/keystore.p12
server.ssl.key-store-password=WER8jl6wer
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

spring.web.resources.static-locations=classpath:/resources/, classpath:/static/, classpath:/static/photo, classpath:/static/file

spring.datasource.url=jdbc:postgresql://localhost:5432/mcpe
spring.datasource.username=mcpe
spring.datasource.password=wer8jl6wer
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

app.jwtSecret=abjksakkdvyavrbhgabdbyarbybvhdvchzbxjcrehdgvvzmxgrcsyvbzdhgfsjdfgbnzxvcvhjyfdg
app.jwtExpirationMs=86400000
app.jwtRefreshExpirationMs=2592000000
app.jwtIssuser=MCPEServer

# user access token insert into api endpoint
app.userAccessToken=chtotebezsesnugno

app.uploadPhotoPath=/home/mcpe/data/photo/
app.uploadFilePath=/home/mcpe/data/files/
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB


app.host=http://minecraftpoketedition.top
logging.file.name = /home/mcpe/serverlog/applog.log